
[[dependencies]]
  name = "github.com/BurntSushi/toml"
  version = "v0.3.0"

[[dependencies]]
  branch = "master"
  name = "github.com/linyows/mflag"

[[dependencies]]
  branch = "master"
  name = "gopkg.in/yaml.v2"
